apiVersion: apps/v1       # Версия API Kubernetes для этого манифеста
kind: Deployment          # Тип объекта, который будет создан этим манифестом
metadata:
  name: fastapi-app
  labels:
    app: fastapi-app
spec:                     # Описываем характеристики deplyment'а
  replicas: 2             # Количество реплик подов
  selector:               # Указываем селектор для пода
    matchLabels:
      app: fastapi-for-students-pod
  template:               # Описываем параметры пода
    metadata:
      labels:
        app: fastapi-for-students-pod
    spec:
      containers:         # Описываем контейнер
      - name: fastapi-for-students
        image: panlukaszgelmintowski/dep:latest
        ports:
        - containerPort: 8000
        env:              # Задаем переменные окружения
        - name: DB_USER   # Некоторые переменные берутся из Secret
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: db-user
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: db-passwd
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: db-name
        - name: DB_HOST  # Эта переменна "обычная", просто задаем значение
          value: "postgres"
        # Указываем команду, которую необходимо выполнить при запуске контейнера
        command: ['bash', '-c', "alembic upgrade head && gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.main:app -b 0.0.0.0:8000"]